# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mana' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Mana
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging'

  target 'ManaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Mana-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Mana-tvOS

  target 'Mana-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
